#!/bin/bash

PID_FILE=/var/run/logsync.pid
NAME=logsync
PROG="/root/staticsync.sh"
USER=root
GROUP=root

start() {
	echo -n "Starting Static Content Syncing"
	if start-stop-daemon --stop --quiet --pidfile $PID_FILE --signal 0
	then
		echo " already running."
		exit
	fi
	start-stop-daemon \
		--start \
		--pidfile $PID_FILE \
		--make-pidfile \
		--background \
		--exec $PROG \
		--user $USER \
		--group $GROUP \
		--chuid $USER \
	echo "."
	return $?
}

stop() {
	echo -n "Stopping Static Content Syncing"
	start-stop-daemon \
		--stop \
		--oknodo \
		--pidfile $PID_FILE
	echo "."
	return $?
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac